/** Russian strings for the Neon Auth UI (only the views we use). */
export const ruAuth = {
  SIGN_IN: "Вход",
  SIGN_IN_ACTION: "Войти",
  SIGN_IN_DESCRIPTION: "Введи почту и пароль",
  EMAIL: "Почта",
  EMAIL_PLACEHOLDER: "имя@example.com",
  EMAIL_REQUIRED: "Нужно ввести почту",
  EMAIL_INSTRUCTIONS: "Введи правильную почту",
  INVALID_EMAIL: "Неправильная почта",
  PASSWORD: "Пароль",
  PASSWORD_PLACEHOLDER: "Пароль",
  PASSWORD_REQUIRED: "Нужно ввести пароль",
  PASSWORD_TOO_SHORT: "Пароль слишком короткий (минимум 8 символов)",
  PASSWORD_TOO_LONG: "Пароль слишком длинный",
  INVALID_PASSWORD: "Неверный пароль",
  INVALID_EMAIL_OR_PASSWORD: "Неверная почта или пароль",
  REMEMBER_ME: "Запомнить меня",
  FORGOT_PASSWORD_LINK: "Забыли пароль?",
  FORGOT_PASSWORD: "Восстановить пароль",
  FORGOT_PASSWORD_ACTION: "Отправить ссылку",
  FORGOT_PASSWORD_DESCRIPTION: "Введи почту — пришлём ссылку для нового пароля",
  FORGOT_PASSWORD_EMAIL: "Проверь почту: там ссылка для нового пароля",
  RESET_PASSWORD: "Новый пароль",
  RESET_PASSWORD_ACTION: "Сохранить пароль",
  RESET_PASSWORD_DESCRIPTION: "Придумай новый пароль",
  RESET_PASSWORD_SUCCESS: "Пароль изменён",
  NEW_PASSWORD: "Новый пароль",
  NEW_PASSWORD_PLACEHOLDER: "Новый пароль",
  NEW_PASSWORD_REQUIRED: "Нужно ввести новый пароль",
  CONFIRM_PASSWORD: "Повтори пароль",
  CONFIRM_PASSWORD_PLACEHOLDER: "Повтори пароль",
  CONFIRM_PASSWORD_REQUIRED: "Нужно повторить пароль",
  PASSWORDS_DO_NOT_MATCH: "Пароли не совпадают",
  INVALID_TOKEN: "Ссылка устарела, запроси новую",
  USER_EMAIL_NOT_FOUND: "Такой почты нет",
  GO_BACK: "Назад",
  CONTINUE: "Продолжить",
  SIGN_OUT: "Выйти",
  OR_CONTINUE_WITH: "или",
  DONT_HAVE_AN_ACCOUNT: "Нет аккаунта?",
  ALREADY_HAVE_AN_ACCOUNT: "Уже есть аккаунт?",
  SIGN_UP: "Регистрация",
  SIGN_UP_ACTION: "Создать аккаунт",
  SIGN_UP_DESCRIPTION: "Введи имя, почту и пароль",
  NAME: "Имя",
  NAME_PLACEHOLDER: "Как тебя зовут",
  NAME_REQUIRED: "Нужно ввести имя",
  USER_ALREADY_EXISTS: "Такая почта уже зарегистрирована",
  EMAIL_OTP: "Код на почту",
  EMAIL_OTP_SEND_ACTION: "Отправить код",
  EMAIL_OTP_VERIFY_ACTION: "Проверить код",
  EMAIL_OTP_DESCRIPTION: "Введи почту — пришлём код",
  EMAIL_OTP_VERIFICATION_SENT: "Проверь почту: там код",
  ONE_TIME_PASSWORD: "Код из письма",
  RESEND_CODE: "Отправить код ещё раз",
  INVALID_OTP: "Неверный код",
  OTP_EXPIRED: "Код устарел",
  TOO_MANY_ATTEMPTS_REQUEST_NEW_CODE: "Слишком много попыток, запроси новый код",
};
